apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: {{ .Values.namespace }} 
spec:
  selector:
    app: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 

