apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - name: cadvisor
        image: {{ .Values.cadvisor.image }} 
        ports:
        - containerPort: 8080 
          name: http
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs:ro
        - name: var-run
          mountPath: /var/run:ro
        - name: sys
          mountPath: /sys:ro
        - name: containerd
          mountPath: /run/containerd:ro
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: containerd
        hostPath:
          path: /run/containerd

