apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }} 
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.grafana.nodePort }}
  selector:
    app: grafana
