apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dashboard-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size }} 
  volumeName: grafana-dashboard-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboard-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.grafana.storage.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.grafana.storage.nfsServer }}
    path: {{ .Values.grafana.storage.nfsPath }}
  persistentVolumeReclaimPolicy: Retain

